// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI3-8wO1o8kMj4bSEs6ovuwygKgvy1JMc',
    appId: '1:26682281372:web:a65a5e88f5c3f1e8cd4c59',
    messagingSenderId: '26682281372',
    projectId: 'flutstore-a1600',
    authDomain: 'flutstore-a1600.firebaseapp.com',
    storageBucket: 'flutstore-a1600.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmc4DQYpp209S0YU7OtnLOTSWBSHtJVIw',
    appId: '1:26682281372:android:0498c52f9f7d336acd4c59',
    messagingSenderId: '26682281372',
    projectId: 'flutstore-a1600',
    storageBucket: 'flutstore-a1600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5-6memgdBYm8SFVV_E5-wsDDBdYW9EcU',
    appId: '1:26682281372:ios:4de05a24b699fcdccd4c59',
    messagingSenderId: '26682281372',
    projectId: 'flutstore-a1600',
    storageBucket: 'flutstore-a1600.appspot.com',
    androidClientId: '26682281372-8b532ovrkbopt5j9q4u9pir359iusnbg.apps.googleusercontent.com',
    iosClientId: '26682281372-g8othes6ivhos27mv1sail5vm1nb0tj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutstore',
  );

}